#%RAML 1.0
title: product-sapi
baseUri: http://localhost:8082
/get-products:
  get:
    responses:
      200:
        body: 
          application/json:
            type: object
            properties:
              "ProductID" : string
              "ProductName" : string
              "ProductProvider" : string
              "ProductDescription" : string
            example: |
              {
                "ProductID" : "12434",
                "ProductName" : "Mule Course 4.x",
                "ProductProvider" : "Mule Soft",
                "ProductDescription" : "Hello, This is new course"
              }

